# Generated by Django 5.0.6 on 2024-07-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectelement',
            name='total_fragments',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='completed_fragments',
            field=models.IntegerField(default=0),
        ),
    ]
