# Generated by Django 5.0.6 on 2024-07-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0002_subjectelement_total_fragments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectelement',
            name='total_fragments',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='total_fragments',
            field=models.IntegerField(default=1),
        ),
    ]
