# Generated by Django 5.0.6 on 2024-07-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0004_add_slug_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
