# Generated by Django 5.0.6 on 2024-07-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_rename_greeting_text_person_greeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mail',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
