# Generated by Django 5.0.6 on 2024-07-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_person_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mail',
            field=models.CharField(default='', max_length=100),
        ),
    ]
