# Generated by Django 5.0.6 on 2024-07-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='body',
        ),
        migrations.AddField(
            model_name='material',
            name='classes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='material',
            name='labs',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='material',
            name='lectures',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='material',
            name='projects',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
